import type { Localized } from "./content.types";
import type { GoalzyMarketingCopy } from "./goalzy-content.types";

export const goalzyMarketingContent = {
  en: {
    title: "Goalzy — Turn choices into games",
    description: "Goalzy settles everyday choices through colorful, sports-inspired matches for 2 to 8 options.",
    eyebrow: "The game that decides for you",
    heading: "Some decisions need a match.",
    introduction: "Where should you eat? What should you watch? Who goes first? Goalzy turns everyday choices into lively sports-inspired games—and lets the action decide.",
    appStoreAction: "Download on the App Store",
    stepsHeading: "How it works",
    steps: [
      { title: "Add your choices", description: "Enter 2 to 8 options you want to settle." },
      { title: "Make them yours", description: "Choose a name, emoji, and any color for each option." },
      { title: "Pick a game mode", description: "Choose a quick goal, a target score, or a timed match." },
      { title: "Watch Goalzy decide", description: "Follow the arena and discover the winner." },
      { title: "Keep the result", description: "Share a colorful card or revisit the decision later in your history. Your choices stay on your device." },
    ],
    modesHeading: "Four ways to decide",
    modesIntroduction: "Every choice enters a playful arena whose rules, scenery, and action change with the selected sport or discipline.",
    versionHeading: "Updated for Goalzy 1.3.0",
    versionNotice: "Pétanque Arcade, rugby, boxing, MMA, and sumo are available in version 1.3.0 and later. Update Goalzy if you do not see them yet.",
    modes: [
      { title: "Golden Goal", description: "The quickest option: the first choice to score wins." },
      { title: "Winning Score", description: "Race to 7 in tennis, 11 in table tennis, exactly 13 in Pétanque Arcade, or 25 in Beach Volley." },
      { title: "Regulation Time", description: "Play basketball, handball, rugby, or football. A tie ends in Golden Goal." },
      { title: "Combat", description: "Choose boxing, MMA, or sumo. The last choice still in play wins." },
    ],
    sportsHeading: "Twelve arena experiences",
    sports: ["Golden Goal", "Football", "Basketball", "Handball", "Rugby", "Tennis", "Table tennis", "Pétanque Arcade", "Beach Volley", "Boxing", "MMA", "Sumo"],
    benefits: ["Custom emojis and colors", "Shareable result cards", "Your decisions stay on your device", "No account required"],
    usefulLinksHeading: "Useful information",
  },
  fr: {
    title: "Goalzy — Le jeu qui décide pour vous",
    description: "Goalzy départage vos choix du quotidien dans des matchs sportifs hauts en couleur réunissant 2 à 8 options.",
    eyebrow: "Le jeu qui décide pour vous",
    heading: "Certains choix ont besoin d’un match.",
    introduction: "Où manger ? Que regarder ? Qui commence ? Goalzy transforme vos choix du quotidien en jeux sportifs animés et laisse le match trancher.",
    appStoreAction: "Télécharger dans l’App Store",
    stepsHeading: "Comment ça marche ?",
    steps: [
      { title: "Ajoutez vos choix", description: "Saisissez de 2 à 8 options à départager." },
      { title: "Personnalisez-les", description: "Choisissez le nom, l’emoji et la couleur de chaque option." },
      { title: "Choisissez un mode", description: "Optez pour un but rapide, un score cible ou un match chronométré." },
      { title: "Regardez Goalzy trancher", description: "Suivez l’arène et découvrez le gagnant." },
      { title: "Gardez le résultat", description: "Partagez une carte colorée ou retrouvez la décision plus tard dans votre historique. Vos choix restent sur votre appareil." },
    ],
    modesHeading: "Quatre façons de décider",
    modesIntroduction: "Chaque choix entre dans une arène ludique dont les règles, le décor et l’action changent selon le sport ou la discipline sélectionnés.",
    versionHeading: "Mis à jour pour Goalzy 1.3.0",
    versionNotice: "La Pétanque Arcade, le rugby, la boxe, le MMA et le sumo sont disponibles à partir de la version 1.3.0. Mettez Goalzy à jour si vous ne les voyez pas encore.",
    modes: [
      { title: "But en or", description: "L’option la plus rapide : le premier choix qui marque gagne." },
      { title: "Score gagnant", description: "Atteignez 7 au tennis, 11 au ping-pong, exactement 13 à la Pétanque Arcade ou 25 au Beach Volley." },
      { title: "Temps réglementaire", description: "Jouez au basket, au handball, au rugby ou au football. Une égalité se termine en but en or." },
      { title: "Combats", description: "Choisissez la boxe, le MMA ou le sumo. La dernière option encore en jeu gagne." },
    ],
    sportsHeading: "Douze expériences d’arène",
    sports: ["But en or", "Football", "Basket", "Handball", "Rugby", "Tennis", "Ping-pong", "Pétanque Arcade", "Beach Volley", "Boxe", "MMA", "Sumo"],
    benefits: ["Emojis et couleurs personnalisables", "Résultats prêts à partager", "Vos décisions restent sur votre appareil", "Aucun compte requis"],
    usefulLinksHeading: "Informations utiles",
  },
} as const satisfies Localized<GoalzyMarketingCopy>;
